###SECTION 1####
library(tidyverse)
library(dslabs)
#unix commands
# pwd : path working directory
# ls : list directory content
# mkdir : make directory
#rmdir : remove directory
# rm -r folder_name  #remove dir that is not empty, "r" stands for recursive
# cd: change dir
# ../ # two dots represents parent dir
# . # single dot represents current workingdir 
# cd ~/projects # concatenate with forward slashes
# cd ../.. # change to two parent layer beyond
# cd -  # whatever dir you were before
# cd  # return to the home dir
# mv path-to-file path-to-destination-directory
# rm filename-1 filename-2 filename-3
# less : opens up a file in your working directory

########## In RStudio ########
# pick existing directory as new project
getwd()    # to confirm current working directory
save()    # save into .rda file, .RData is also fine but less preferred
ggsave("figs/barplot.png")    # save a plot generated by ggplot2 to a dir called "figs"


###SECTION 3### R markdown
# a sample code chunk
# ```{r}
# summary(pressure)
# ```
# # When echo=FALSE, code will be hided in output file
# ```{r echo=FALSE}
# summary(pressure)
# ```
# # use a descriptive name for each chunk for debugging purpose
# ```{r pressure-summary}
# summary(pressure)
# ```

